version: '3.7'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"

  logstash:
    image: docker.elastic.co/logstash/logstash:7.10.1
    container_name: logstash
    volumes:
      - ./data_processing/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    depends_on:
      - kafka
      - elasticsearch
    ports:
      - "5000:5000"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - siem_network

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.1
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"

  elastalert:
    image: bitsensor/elastalert:latest
    depends_on:
      - elasticsearch
    ports:
      - "3030:3030"
    volumes:
      - ./alerting/rules:/opt/elastalert/rules
      - ./alerting/config.yaml:/opt/elastalert/config.yaml

  fluentd:
    build:
      context: ./data_collection
      dockerfile: Dockerfile
    container_name: fluentd
    volumes:
      - ./data_collection/fluent.conf:/fluentd/etc/fluent.conf
      - /var/log:/var/log
    depends_on:
      - kafka
    networks:
      - siem_network

  ml_anomaly_detection:
    build:
      context: ./ml
      dockerfile: Dockerfile
    container_name: ml_anomaly_detection
    ports:
      - "8000:8000"
    depends_on:
      - elasticsearch
    networks:
      - siem_network

volumes:
  esdata:

networks:
  siem_network:
    driver: bridge

