version: '3.8'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - siem-network

  beats:
    image: elastic/beats:7.10.0
    volumes:
      - ./collectors/beats/config:/usr/share/beats/beat/config
    networks:
      - siem-network

  fluentd:
    image: fluent/fluentd:v1.8-1
    volumes:
      - ./collectors/fluentd/config:/fluentd/etc
    networks:
      - siem-network

  logstash:
    image: docker.elastic.co/logstash/logstash:7.10.0
    volumes:
      - ./collectors/logstash/pipeline:/usr/share/logstash/pipeline
    networks:
      - siem-network

  kafka:
    image: wurstmeister/kafka:latest
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9094
      KAFKA_ZOOKEEPER: zookeeper:2181
    networks:
      - siem-network

  zookeeper:
    image: wurstmeister/zookeeper:latest
    networks:
      - siem-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    environment:
      discovery.type: single-node
    networks:
      - siem-network

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.0
    ports:
      - "5601:5601"
    networks:
      - siem-network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    networks:
      - siem-network

  elastalert:
    image: jertel/elastalert:latest
    volumes:
      - ./monitoring/elastalert/config:/opt/elastalert/config
    networks:
      - siem-network

networks:
  siem-network:
    driver: bridge